allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@types/node@26.1.1'
patchedDependencies:
  "@convex-dev/auth@0.0.94": patches/@convex-dev__auth@0.0.94.patch
